export const CREATE_TODO_STARTED = 'CREATE_TODO_STARTED';
export const CREATE_TODO_COMPLETE = 'CREATE_TODO_COMPLETE';
export const CREATE_TODO_FAIL = 'CREATE_TODO_FAIL';

export const READ_TODO_STARTED = 'READ_TODO_STARTED';
export const READ_TODO_COMPLETE = 'READ_TODO_COMPLETE';
export const READ_TODO_FAIL = 'READ_TODO_FAIL';

export const UPDATE_TODO_STARTED = 'UPDATE_TODO_STARTED';
export const UPDATE_TODO_COMPLETE = 'UPDATE_TODO_COMPLETE';
export const UPDATE_TODO_FAIL = 'UPDATE_TODO_FAIL';

export const DELETE_TODO_STARTED = 'DELETE_TODO_STARTED';
export const DELETE_TODO_COMPLETE = 'DELETE_TODO_COMPLETE';
export const DELETE_TODO_FAIL = 'DELETE_TODO_FAIL';
